#
# This is the super Makefile for ALL ARC_API libraries.
#

API_BASE	=   	/home/hstecher/controller_test/ARC_API/3.5	

all:
#	$(MAKE) -f Makefile_x32
	$(MAKE) -f Makefile_x64

cpplibs:
#	$(MAKE) -f Makefile_x32 cpplibs
	$(MAKE) -f Makefile_x64 cpplibs

jnilibs:
#	$(MAKE) -f Makefile_x32 jnilibs
	$(MAKE) -f Makefile_x64 jnilibs

