stages:
 - build
build_image:
 stage: build
 image: docker:latest
 services:
   - docker:dind
 script:
   - docker build -t gnirsdc-lib-env -f Dockerfile_rocky8 .
   - docker run --rm -v .:/repo gnirsdc-lib-env bash -l -c "cd /repo && make clean all" 
   - git commit -am"pipeline generated commit of shared libraries [skip ci]" 
   - git push
 rules:
   - if: '$CI_COMMIT_BRANCH == "pybind11"'
