stages:
 - build
before_script:
 - 'git remote set-url origin https://oauth2:$GIT_TOKEN@gitlab.com/nsf-noirlab/gemini/rtsw/iocs/gnirsdc-lib.git'
build_image:
 stage: build
 image: docker:latest
 services:
   - docker:dind

 script:
   - docker build  --build-arg "TOKEN=${GIT_TOKEN}" --build-arg "EMAIL=${GITLAB_USER_EMAIL}" --build-arg "NAME=${GITLAB_USER_NAME}" -t gnirsdc-lib-env -f Dockerfile_rocky8 .

 rules:
   - if: '$CI_COMMIT_BRANCH == "pybind11"'
