CPPFLAGS=-std=c++11 -I/home/hstecher/local/include -I/usr/include/json-c12 -Wall -g  -Werror 
LDFLAGS=-L/usr/local/lib/arc -g -Wl,-rpath=/usr/local/lib/arc 
LDLIBS=-lCArcDevice -lCArcDeinterlace -lCArcFitsFile -lcfitsio -ljson-c12 -luuid -lpthread

TARGETS=testing continuous unified libgnirsdc.a# rtest ptest
CPPDEPS=libgnirs.cpp
HDEPS=libgnirs.h

all: $(TARGETS)

libgnirsdc.a: unified.cpp $(CPPDEPS) 
	ar rcs $@ $^

%: %.cpp $(CPPDEPS) $(HDEPS)
	g++ $(CPPFLAGS) $(LDFLAGS) $(LDLIBS) $< $(CPPDEPS) -o $@

	

clean:
	rm -f $(TARGETS)
